### ISSUE TITLE
"razor pages website" link in WebApplicationFillForm section of readme opens Microsoft documentation page:)

### ISSUE THREAD

**Issue by DaniilVeriga** [kevbite/Kevsoft.PDFtk#17]

**Comment by kevbite** [comment]
I can see why that's confusing but it's a link to say what a razor pages site is, the link for the samples folder is above 😂 I'll update it anyway to make it less confusing. Thanks

**Comment by kevbite** [comment]
Just got round to updating the readme. Thanks
