### ISSUE TITLE
Examples in readme.md are missing await operators

### ISSUE THREAD

**Issue by DavidBetteridge** [kevbite/Kevsoft.PDFtk#2]
Some of the examples need to include a second await operator.

For example
`var result = await pdFtk.GetDataFieldsAsync(File.ReadAllBytesAsync("Form.pdf"));`

should be

```
var fileBytes=  await File.ReadAllBytesAsync("Form.pdf")
var result = await pdFtk.GetDataFieldsAsync(fileBytes);`

```

**Comment by kevbite** [comment]
Examples have been updated 👍  thanks for raising!
