### ISSUE TITLE
Possibility to include PDF signature 

### ISSUE THREAD

**Issue by iamSathishMohan** [kevbite/Kevsoft.PDFtk#4]
Wanted to check is it possible to include the support for the PDF Signature field. Either the image signature or digital signature.

**Comment by kevbite** [comment]
If it's supported by [pdftk-server](https://www.pdflabs.com/tools/pdftk-server/) then it will work, if not then we won't support it.

**Comment by kevbite** [comment]
This might be useful? https://gist.github.com/chrpinedo/a2a2af757e96aec0d6f69d707629a01a

**Comment by kevbite** [comment]
I'm going to close this issue off for the time being, feel free to open another if required.
